/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webservice_UserService */

#ifndef _Included_com_webservice_UserService
#define _Included_com_webservice_UserService
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
