/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webservice_cppCaller */

#ifndef _Included_com_webservice_cppCaller
#define _Included_com_webservice_cppCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webservice_cppCaller
 * Method:    call
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_webservice_cppCaller_call
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
